server:
  port: 8082

spring:
  application:
    name: users-service

  # nacos服务注册与配置中心
  config:
    import: nacos:${spring.application.name}
  cloud:
    nacos:
      server-addr: ${NACOS_ADDRESS}
      discovery:
        namespace: ${NACOS_NAMESPACE}
      config:
         file-extension: yaml
    # OpenFeign configuration
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

  # 数据库连接池配置
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}





mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cehnzhihao.users.domain.po
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    root: INFO
    com.example.users: DEBUG
    org.apache.dubbo: INFO
    com.alibaba.nacos: WARN

#jwt相关配置
jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: ${JWT_SECRET_KEY}
    # 设置jwt过期时间
    user-ttl: 604800000
    # 设置前端传递过来的令牌名称
    token-name: token
    # 设置后端jwt校验的token名称
    header-name: userId