server:
  port: 8082

spring:
  application:
    name: users-service

  # nacos服务注册与配置中心
  config:
    import: nacos:${spring.application.name}
  cloud:
    nacos:
      server-addr: ${nacos.address}
      discovery:
        namespace: ${cloud.nacos.namespace}
      config:
         file-extension: yaml
  profiles:
    active: dev # 激活开发环境配置

  # kafka相关配置
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:122.51.149.223:9092}
    producer:
      retries: 3 #设置大于0，会将发送失败的记录重新发送
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500

    listener:
      ack-mode: manual_immediate
  # 数据库连接池配置
  datasource:
    url: jdbc:mysql://${cs.db.host}:3306/${cs.db.name}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${cs.db.user}
    password: ${cs.db.pwd}



# dubbo + nacos 服务注册发现
nacos:
    address: ${NACOS_ADDRESS:121.43.197.241:8848}
    #  117.72.124.24:8849
dubbo:
  protocol:
    port: -1
  consumer:
    check: false
  registry:
    address: nacos://${nacos.address}?username=nacos&password=nacos&namespace=${dubbo.nacos.namespace}
    register-mode: application
  application:
    qos-enable: off
    name: ${spring.application.name}-dubbo


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cehnzhihao.users.domain.po
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    root: INFO
    com.example.users: DEBUG
    org.apache.dubbo: INFO
    com.alibaba.nacos: WARN

#jwt相关配置
jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: ${JWT_SECRET_KEY:cloud_shopdh21hadxy812yhdahd1r31}
    # 设置jwt过期时间
    user-ttl: 604800000
    # 设置前端传递过来的令牌名称
    token-name: token
    # 设置后端jwt校验的token名称
    header-name: userId