cs:
  db:
    host: ${DB_HOST:117.72.124.24}
    name: ${DB_NAME:summer}
    user: ${DB_USER:summer}
    pwd: ${DB_PASSWORD:summer}

dubbo:
  nacos:
    namespace: ${DUBBO_NACAS_NAMESPACE:hqh}

cloud:
  nacos:
    namespace: ${NACOS_NAMESPACE:hqh}
