server:
  port: 8081

spring:
  profiles:
    default: dev
  application:
    name: orders-service
  config:
    import: nacos:order-service
  cloud:
    nacos:
      discovery:
        namespace: ${NACOS_NAMESPACE}
      server-addr: 122.51.149.223:8848
      config:
          file-extension: yaml
      username: nacos
      password: nacos
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
  # 数据库连接池配置
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:}
    database: ${REDIS_DATABASE}
    password: ${REDIS_PASSWORD}





mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cehnzhihao.users.domain.po
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    root: INFO
    com.example.orders: DEBUG
    org.apache.dubbo: INFO
    com.alibaba.nacos: WARN