server:
  port: 8081

spring:
  application:
    name: orders-service
  config:
    import: nacos:${spring.application.name}
  cloud:
    nacos:
      server-addr: ${nacos.address}
      config:
          file-extension: yaml
# dubbo + nacos 服务注册发现
nacos:
    address: 121.43.197.241:8848
      #  117.72.124.24:8849
dubbo:
  protocol:
    port: -1
  consumer:
    check: false
  registry:
    address: nacos://${nacos.address}?username=nacos&password=nacos
    register-mode: instance
  application:
    qos-enable: off
    name: ${spring.application.name}
  # 数据库连接池配置
  datasource:
    url: jdbc:mysql://${cs.db.host}:3306/${cs.db.name}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${cs.db.user}
    password: ${cs.db.pwd}

# 激活默认profile（可选）
spring.profiles.active: dev

profiles:
  active: dev # 激活开发环境配置

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cehnzhihao.users.domain.po
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    root: INFO
    com.example.orders: DEBUG
    org.apache.dubbo: INFO
    com.alibaba.nacos: WARN