cs:
  db:
    host: 117.72.124.24
    name: summer
    user: summer
    pwd: summer

dubbo:
  registry:
    namespace: hqh

cloud:
  nacos:
    namespace: hqh

xxl:
  job:
    admin:
      accessToken: default_token
      addresses: http://127.0.0.1:8088/xxl-job-admin