server:
  port: 8083

spring:
  application:
    name: products-service
  config:
    import: nacos:${spring.application.name}
  cloud:
    nacos:
      server-addr: ${nacos.address}
      discovery:
        namespace: ${cloud.nacos.namespace}
      config:
        file-extension: yaml
  # 数据库连接池配置
  datasource:
    url: jdbc:mysql://${cs.db.host}:3306/${cs.db.name}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${cs.db.user}
    password: ${cs.db.pwd}
  profiles:
    active: dev



  redis:
    host: 121.43.197.241
    port: 16379
    database: 0
# OpenFeign configuration
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000



mybatis-plus:
  mapper-locations: classpath*:mapper/mp/*.xml
  type-aliases-package: com.chenzhihao.products.domain.po
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto



logging:
  level:
    root: INFO
    com.example.products: DEBUG
    org.apache.dubbo: WARN
    com.alibaba.nacos: WARN