server:
  port: 8080
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
#nacos服务注册与配置中心
  config:
    import: nacos:${spring.application.name}
  cloud:
    nacos:
      server-addr: ${nacos.address}
      discovery:
        namespace: ${cloud.nacos.namespace}
      config:
        file-extension: yaml
# gateway相关配置
    gateway:
      routes:  # 路由配置
        - id: users-service # 路由规则id,可自定义，但必须唯一
          uri:
            lb://users-service # 路由的目标服务，lb代表负载均衡，会从注册中心获取服务实例列表，然后进行负载均衡
          predicates:
            - Path=/users/** # 路由的条件，这里是路径匹配，只有路径以/user开头的请求才会被路由到users-service服务

        - id: products-service # 路由规则id,可自定义，但必须唯一
          uri:
            lb://products-service # 路由的目标服务，lb代表负载均衡，会从注册中心获取服务实例列表，然后进行负载均衡
          predicates:
            - Path=/commodity/** # 路由的条件，这里是路径匹配，只有路径以/user开头的请求才会被路由到users-service服务

        - id: carts-service # 路由规则id,可自定义，但必须唯一
          uri:
            lb://carts-service # 路由的目标服务，lb代表负载均衡，会从注册中心获取服务实例列表，然后进行负载均衡
          predicates:
            - Path=/cart/** # 路由的条件，这里是路径匹配，只有路径以/user开头的请求才会被路由到users-service服务

        - id: orders-service # 路由规则id,可自定义，但必须唯一
          uri:
            lb://orders-service # 路由的目标服务，lb代表负载均衡，会从注册中心获取服务实例列表，然后进行负载均衡
          predicates:
            - Path=/orders/** # 路由的条件，这里是路径匹配，只有路径以/user开头的请求才会被路由到users-service服务

# dubbo + nacos 服务注册发现
nacos:
  address: 121.43.197.241:8848
  #  117.72.124.24:8849

#jwt相关配置
jwt:
  # 设置jwt签名加密时使用的秘钥
  secret-key: cloud_shopdh21hadxy812yhdahd1r31
  # 设置jwt过期时间
  user-ttl: 604800000
  # 设置前端传递过来的令牌名称
  token-name: token
  # 设置后端jwt校验的token名称
  claim-name: userId
# 不用登录校验的路径
auth:
  excludePaths:
    - /users/login
    - /users/register
    - /commodity/search
    - /commodity/get/**