cs:
  db:
    host: ${DB_HOST:117.72.124.24}
    name: ${DB_NAME:summer}
    user: ${DB_USER:summer}
    pwd: ${DB_PASSWORD:summer}

dubbo:
  registry:
    namespace: ${DUBBO_REGISTRY_NAMESPACE}

cloud:
  nacos:
    namespace: ${NACOS_NAMESPACE}