server:
  port: 8084

spring:
  application:
    name: carts-service
  config:
    import: nacos:${spring.application.name}
  cloud:
    nacos:
      server-addr: ${NACOS_ADDRESS}
      discovery:
        namespace: ${NACOS_NAMESPACE}
      config:
        file-extension: yaml
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
  # 数据库连接池配置
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}



  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:}
    database: ${REDIS_DATABASE}
    password: ${REDIS_PASSWORD}


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cehnzhihao.carts.domain.po
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    root: INFO
    com.example.products: DEBUG
    org.apache.dubbo: WARN
    com.alibaba.nacos: WARN