server:
  port: 8084

spring:
  application:
    name: carts-service
  config:
    import: nacos:${spring.application.name}
  cloud:
    nacos:
      server-addr: ${nacos.address}
      discovery:
        namespace: ${cloud.nacos.namespace}
      config:
        file-extension: yaml
  # 数据库连接池配置
  datasource:
    url: jdbc:mysql://${cs.db.host}:3306/${cs.db.name}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${cs.db.user}
    password: ${cs.db.pwd}
  profiles:
    active: dev


  redis:
    host: ${REDIS_HOST:117.72.124.24}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}

# dubbo + nacos 服务注册发现
nacos:
  address: ${NACOS_ADDRESS:121.43.197.241:8848}
  #  117.72.124.24:8849
dubbo:
  protocol:
    port: -1
  consumer:
    timeout: 5000
    check: false
  registry:
    address: nacos://${nacos.address}?username=nacos&password=nacos&namespace=${dubbo.registry.namespace}
    register-mode: instance
  application:
    qos-enable: off
    name: ${spring.application.name}-dubbo



mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cehnzhihao.carts.domain.po
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    root: INFO
    com.example.products: DEBUG
    org.apache.dubbo: WARN
    com.alibaba.nacos: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients: WARN